// <auto-generated />
using System;
using Ecommerce.System.Infrastructure.Persistence.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415184048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.System.Core.Models.AtrybutWariantu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Klucz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WariantProduktuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Wartosc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WariantProduktuId");

                    b.ToTable("Atrybuty");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.Klient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumerTelefonu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.PozycjaZamowienia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CenaWChwiliZakupu")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Ilosc")
                        .HasColumnType("integer");

                    b.Property<Guid>("WariantProduktuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZamowienieId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PozycjeZamowienia");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.Produkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.WariantProduktu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProduktId")
                        .HasColumnType("uuid");

                    b.Property<int>("StanMagazynowy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduktId");

                    b.ToTable("Warianty");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.Zamowienie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresDostawy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CalkowitaWartosc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KlientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.AtrybutWariantu", b =>
                {
                    b.HasOne("Ecommerce.System.Core.Models.WariantProduktu", null)
                        .WithMany("Atrybuty")
                        .HasForeignKey("WariantProduktuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.WariantProduktu", b =>
                {
                    b.HasOne("Ecommerce.System.Core.Models.Produkt", null)
                        .WithMany("Warianty")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.Produkt", b =>
                {
                    b.Navigation("Warianty");
                });

            modelBuilder.Entity("Ecommerce.System.Core.Models.WariantProduktu", b =>
                {
                    b.Navigation("Atrybuty");
                });
#pragma warning restore 612, 618
        }
    }
}
